config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: 'users/registrations', omniauth_callbacks: 'users/omniauth_callbacks' }

  resources :users
  root 'application#home'

  scope '/friends', as: :friends do
    get 'find', to: 'users#find_friends'
    get 'requests', to: 'users#friend_requests'
  end

  resources :friend_requests, only: :create do
    member do
      post 'confirm'
      delete 'delete'
    end
  end

  get 'friends', to: 'users#friends', as: :friends
  scope '/friends', as: :friends do
    get 'find', to: 'users#find_friends'
    get 'requests', to: 'users#friend_requests'
  end

  get 'search', to: 'static_pages#search'

  resources :posts
  resources :comments
resources :likes
end

app/models/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def search
    @query = params[:query].downcase
    @users = User.where('LOWER(email) LIKE ?', "%#{@query}%")
                 .order(:email)
  end
end

app/views/static_pages/_search_form.html.erb
<%= form_with(url: search_path, method: :get, local: true, class: 'form-inline my-2 my-lg-0') do |f| %>
    <div class="form-group mb-2">
        <%= f.text_field :query, placeholder: "Search your friends here...", class: 'form-control mr-sm-2'%>
        <%= button_tag type: 'submit', class: 'btn btn-outline-primary mr-sm-2' do %>
            Submit
        <% end %>
    </div>
<% end %>

app/views/static_pages/search.html.erb
<div class='container'>
  <h2>Search results for "<i><%= @query %></i>"</h2>

  <div>
    <% if @users.empty? || @users.length == User.all.length %>
      No matching results!
    <% else %>
      There are <%= @users.length %> matching profiles!

      <% @users.each do |user| %>
        <div>
          <div class="card" style="width: 18rem;">
            <% if user == current_user %>
              <div class="card-header"><%= link_to user.username, user %> <strong>(YOU)</strong></div>
              <div class="card-body">[<%= user.email %>]</div>
              
            <% else %>
              <div class="card-header"><%= link_to user.username, user %></div>
              <div class="card-body">
                [<%= user.email %>]
                <% if user_signed_in? %>
                  <% if !check_friendship(current_user, user) && FriendRequest.where(sender_id: current_user.id, recipient_id: user.id).empty? %>
                    <%= button_to "Add Friend", friend_requests_path, method: :post, params: {recipient_id: user.id, query: params[:query]}, class: "btn btn-dark ml-2" %>
                  <% elsif check_friendship(current_user, user) %>
                    <i>(Your friend)</i>
                  <% elsif !FriendRequest.where(sender_id: current_user.id, recipient_id: user.id).empty? %>
                    <i>(Pending request...)</i>
                  <% end %>
                <% end %>
              </div>
            <% end %>
          </div>
          <br>
        </div>
      <% end %>
    <% end %>
  </div>
  <br>
</div>