config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: 'users/registrations', omniauth_callbacks: 'users/omniauth_callbacks' }

  resources :users
  root 'application#home'

  scope '/friends', as: :friends do
    get 'find', to: 'users#find_friends'
    get 'requests', to: 'users#friend_requests'
  end

  resources :friend_requests, only: :create do
    member do
      post 'confirm'
      delete 'delete'
    end
  end

  get 'friends', to: 'users#friends', as: :friends
  scope '/friends', as: :friends do
    get 'find', to: 'users#find_friends'
    get 'requests', to: 'users#friend_requests'
  end

  get 'search', to: 'static_pages#search'

  resources :posts
  resources :comments
resources :likes
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id                     :integer          not null, primary key
#  email                  :string           default(""), not null
#  encrypted_password     :string           default(""), not null
#  reset_password_token   :string
#  reset_password_sent_at :datetime
#  remember_created_at    :datetime
#  created_at             :datetime         not null
#  updated_at             :datetime         not null
#  name                   :string
#  birthday               :datetime
#  education              :string
#  workplace              :string
#
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_initialize do |user|
      user.email = auth.info.email
      user.password = Devise.friendly_token[0, 20]
      user.name = auth.info.name # assuming the user model has a name
      # If you are using confirmable and the provider(s) you use validate emails, 
      # uncomment the line below to skip the confirmation emails.
      # user.skip_confirmation!
    end
  end

  def self.new_with_session(params, session)
    super.tap do |user|
      # binding.pry
      if data = session["devise.facebook_data"] && session["devise.facebook_data"]["extra"]["raw_info"] ||
        data = session["devise.github_data"] && session["devise.github_data"]["info"]
        user.name = data["name"] if user.name.blank?
        user.email = data["email"] if user.email.blank?
      end
    end
  end

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :omniauthable, omniauth_providers: %i[facebook github]

  has_many :friend_invitations,
            foreign_key: :recipient_id,
            class_name: 'FriendRequest',
            dependent: :destroy

  has_many :friend_requests,
            foreign_key: :sender_id,
            dependent: :destroy
  
  has_many :friendships,
            foreign_key: :friend_a_id,
            dependent: :destroy

  has_many :posts,
            foreign_key: :author_id,
            dependent: :destroy

  has_many :likes, 
           dependent: :destroy

  has_many :comments,
            foreign_key: :author_id,
            dependent: :destroy
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # See https://github.com/omniauth/omniauth/wiki/FAQ#rails-session-is-clobbered-after-callback-on-developer-strategy
  skip_before_action :verify_authenticity_token, only: [:facebook]

  def facebook
    # You need to implement the method below in your model (e.g. app/models/user.rb)
    @user = User.from_omniauth(request.env["omniauth.auth"])
    if @user.persisted?
      sign_in_and_redirect @user, event: :authentication # this will throw if @user is not activated
      set_flash_message(:notice, :success, kind: "Facebook") if is_navigational_format?
    else
      session["devise.facebook_data"] = request.env["omniauth.auth"].except(:extra) # Removing extra as it can overflow some session stores
      redirect_to new_user_registration_url
    end
  end

  def github
    # You need to implement the method below in your model (e.g. app/models/user.rb)
    @user = User.from_omniauth(request.env["omniauth.auth"])
    if @user.persisted?
      sign_in_and_redirect @user, event: :authentication # this will throw if @user is not activated
      set_flash_message(:notice, :success, kind: "Github") if is_navigational_format?
    else
      session["devise.github"] = request.env["omniauth.auth"].except(:extra) # Removing extra as it can overflow some session stores
      redirect_to new_user_registration_url
    end
  end

  def failure
    redirect_to root_path
  end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
  after_action :send_new_account_email, only: :create, if: -> { @user.persisted? }
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!

  def friends
    @user = current_user
    @friends = []
    @user.friendships.each do |friendship| 
      @friends << User.find(friendship.friend_b_id)
    end
  end

  def show 
    @user = User.find(params[:id])
    @posts = @user.posts
  end

  def friend_requests
    @invitations = current_user.friend_invitations
  end

  def find_friends
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_like.html.erb
<div class="card w-25" style="padding: 3px">
    <% @like = Like.where(user_id: current_user.id, likable_id: object.id, likable_type: object.class.to_s) %>
    <div style="font-size: 14px">
        <strong><%= pluralize(object.likes.length, 'like') %></strong>
        <% if object.likes.length > 0 %>
            by 
            <% object.likes.each_with_index do |like, index| %>
                <% if index == object.likes.length - 1 %>
                    <%= like.user.username %>.
                <% else %>
                    <%= like.user.username %>, 
                <% end %>
            <% end %>
        <% end %>
    </div>
    <% if @like == [] %>
        <%= form_with(model: Like.new, local: true) do |form| %>
            <div class='d-flex' style='align-items: center'>
                <%= form.hidden_field :likable_id, value: object.id %>
                <%= form.hidden_field :likable_type, value: object.class.to_s %>
                <%= form.hidden_field :user_id, value: current_user.id %>
                <%= form.submit "Like", class: 'btn btn-success', style: 'font-size: 14px; padding: 3px' %>
            </div>
        <% end %>
    <% else %>
        <%= button_to "Dislike", @like[0], method: :delete, class: 'btn btn-dark', style: 'font-size: 14px; padding: 3px' %>
    <% end %>
</div>

app/views/users/_posts.html.erb
<% posts.each do |post| %>
    <div class="card mb-3" style="width:75rem">
        <h3 class="card-header d-flex justify-content-between">
            <%= User.find(params[:id]).username %> - <%= post.title %><br>
            <div class="d-flex justify-content-between", style="width: 12rem">
                <% if current_user == post.author %>
                    <%= link_to "Edit post", edit_post_path(post), class: 'btn btn-secondary mb-2' %>
                    <%= button_to "Delete post", post, method: :delete, class: 'btn btn-danger', style: 'display: inline' %>
                <% end %>
            </div>
        </h3>
        <div class="card-body">
            <blockquote class="blockquote mb-0" style="font-size: 25px"><%= post.description %></blockquote>
            <%= render 'like', object: post %>
        </div>
        <div class="card-footer">
            <strong>Comments:</strong><br>
            <% if !post.comments.empty? %>
                <% post.comments.each do |comment| %>
                    <div class='d-flex' style='align-items: center' >
                        <strong><%= comment.author.email %></strong>: <%= comment.content %>
                        <% if comment.author == current_user %>
                            <%= link_to "Edit", edit_comment_path(comment), class: 'ml-3 mr-2' %>
                            <%= button_to "Delete", comment, method: :delete , class: 'btn btn-danger mr-4' %>
                            <%= render 'like', object: comment %>
                        <% end %>
                    </div>
                    <br>
                <% end %>
            <% end %>
            <%= render 'comments/form', post: post %>
        </div>
    </div>
<% end %>

app/views/users/friend_requests.html.erb
<div class='container'>
  <h3>Your Friend Requests</h3>

  <div>
    <% if @invitations.empty? %>
      You have no friend requests right now!
    <% else %>
      <% @invitations.each do |invitation| %>
        <div class="card mb-2" style="width: 22rem;">
          <div class="card-body">
            <h4 class="card-title">
              You have a friend request from:
              <%= invitation.sender.username %>
              <%= link_to invitation.sender.email, user_path(invitation.sender) %>
            </h4>
            <div>
              <div class="d-inline-flex p-2">
                <%= button_to confirm_friend_request_path(invitation),
                            class: 'btn btn-success mb-2 mr-2',
                            method: :post do %>
                  <i>accept</i>
                <% end %>

                <%= button_to delete_friend_request_path(invitation),
                            method: :delete,
                            class: 'btn btn-danger mb-2',
                            data: { confirm: "Delete #{invitation.sender.name}'s friend request?" } do %>
                  <i>reject</i>
                <% end %>
              </div>
            </div>
          </div>
        </div>
      <% end %>
    <% end %>
  </div>
</div>

app/views/users/friends.html.erb
<div class='container'>
  <h3><%= current_user.username %>'s Friends</h3>
  <div>
    <% if @friends.empty? %>
      Currently you have no friends!
    <% else %>
      You have <%= pluralize(@friends.length, 'friend') %>!
    <% end %>

    <% @friends.each do |friend| %>
      <div class="card mb-2" style="width: 22rem">
        <div class="card-body">
          <strong>Username: </strong>
          <%= link_to friend.username, user_path(friend) %>
          <br>
          <strong>Email:</strong> <%= friend.email %>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<div class='container'>
    <% if @user == current_user %>
        <%= link_to "Add a post", new_post_path, class: 'btn btn-outline-dark mb-4' %>
    <% end %>

    <% if @posts.length > 0 %>
        <h1>All <%= @user.username %> posts are listed below:</h1>
        <%= render 'posts', posts: @posts %>
    <% else %>
        <h2>There are no posts available to show now!</h2>
    <% end %>
</div>