config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: 'users/registrations', omniauth_callbacks: 'users/omniauth_callbacks' }

  resources :users
  root 'application#home'

  scope '/friends', as: :friends do
    get 'find', to: 'users#find_friends'
    get 'requests', to: 'users#friend_requests'
  end

  resources :friend_requests, only: :create do
    member do
      post 'confirm'
      delete 'delete'
    end
  end

  get 'friends', to: 'users#friends', as: :friends
  scope '/friends', as: :friends do
    get 'find', to: 'users#find_friends'
    get 'requests', to: 'users#friend_requests'
  end

  get 'search', to: 'static_pages#search'

  resources :posts
  resources :comments
resources :likes
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <ul class="footer-links">
    <li>
      <%= link_to 'https://github.com/ntphuongthao', class: 'footer-link' do %>
        <span>GitHub</span>
        <div class="footer-icon-container">
          <ion-icon class="github-footer" name="logo-github"></ion-icon>
        </div>
      <% end %>
    </li>
    <li>
      <span>2022 &#169;</span>
      Thao Nguyen
    </li>
  </ul>
</footer>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <% if user_signed_in? %>
    <%= link_to "FACEBOOK", current_user, class: "navbar-brand", id: "logo", style: "font-size: 28px;" %>
  <% else %>
    <%= link_to "FACEBOOK", root_path, class: "navbar-brand", id: "logo", style: "font-size: 28px;" %>
  <% end %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if user_signed_in? %>
        <li class="nav-item">
          <%= link_to current_user.username, edit_user_registration_path, class: 'nav-link active'%>
        </li>
        
        <li class="nav-item">
            <%= link_to "All Your Friends", friends_path, class: 'nav-link'%>
        </li>

        <li class="nav-item">
          <%= link_to "Friend Requests", friends_requests_path, class: 'nav-link' %>
        </li>

        <li class="nav-item">
          <%= render 'static_pages/search_form' %>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "Register new Account", new_user_registration_path, class: 'nav-link' %>
        </li>
        
        <li class="nav-item">
          <%= link_to "Log In", new_user_session_path, class: 'nav-link' %>
        </li>

        
      <% end %>
    </ul>

    <% if user_signed_in? %>
      <div class="nav-item">
        <%= button_to "Log Out", destroy_user_session_path, class: 'nav-link btn btn-outline-danger mr-2', :method => "delete" %>
      </div>
    <% else %>
      <div class="nav-item">
        <%= render 'static_pages/search_form' %>
      </div>
    <% end %>
    
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Facebook</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  </head>

  <body style="background-color: rgb(173, 216, 230); font-family: Brush Script MT; font-size: 18px;">
    <%= render 'layouts/navigation' %>

    <% if notice %>
      <div class="alert alert-success" role="alert">
        <p><%= notice %></p>
      </div>
    <% end %>

    <% if alert %>
      <div class="alert alert-danger" role="alert">
        <p><%= alert %></p>
      </div>
    <% end %>
    
    <br><br>
    <%= yield %>
    <!--
    <%= render 'layouts/footer' %>
    -->
  </body>
</html>